# Create a first temporary image named "builder"
FROM golang:1.24.4 AS builder
# Copy Go code (in "builder")
WORKDIR /src/
COPY . .
# Build executables (in "builder")
RUN go build -o /app/webapi ./cmd/webapi

# Create final container
FROM debian:bookworm
# Inform Docker about which port is used
EXPOSE 3000
# Copy the executable from the "builder" image
WORKDIR /app/
COPY --from=builder /app/webapi ./
# Set the default program to our Go backend
CMD ["/app/webapi"]

# How to build and run:
#       docker build -f Dockerfile.backend -t wasa-backend .
#       docker run -it --rm -p 3000:3000 wasa-backend