# This is the configuration file for the API service
# Description of this part is present in the `main.go` file

log:
  level: debug
#  methodname: false
#  json: false
#  destination: stderr
#  file: /tmp/debug.log
#  combinedtostdout: true

# Database configuration - stored in /tmp and cleared on shutdown
db:
  filename: /tmp/decaf.db

#web:
#  apihost: 0.0.0.0:3000
#  debughost: 0.0.0.0:4000
#  readtimeout: 5s
#  writetimeout: 5s
#  shutdowntimeout: 5s
#  behindproxy: false
